version: "3.9"
services:
  triton:
    image: nvcr.io/nvidia/tritonserver:24.12-py3
    container_name: triton_server
    runtime: nvidia
    ports:
      - "8000:8000"  # HTTP
      - "8001:8001"  # gRPC
      - "8002:8002"  # Metrics
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - HF_TOKEN=${HF_TOKEN}
    command:
      - bash
      - -c
      - |
        set -e
        pip install -q huggingface_hub
        
        hf download vsuman-ai/bertweet-sentiment-triton-onnx \
          --repo-type model \
          --local-dir /models
        
        rm -rf /models/.cache /root/.cache/huggingface
        
        tritonserver --model-repository=/models

    volumes:
      - triton_models:/models
    restart: unless-stopped
  sentiment:
    container_name: sentiment
    image: ai-sentiment:latest
    ports:
      - "3000:3000"
    build:
      dockerfile: ../ops/docker_from_pex.Dockerfile
      context: ../../dist
      args:
        deps_pex: ai.sentiment/app-deps@parametrize=cpu.pex
        srcs_pex: ai.sentiment/app-srcs@parametrize=cpu.pex
    environment:
      - SENTIMENT_MODEL_ID=${SENTIMENT_MODEL_ID}
      - TRITON_INFERENCE_URL=triton:8001
    command: >
      /opt/app/pex run_app_parser
  #      /opt/app/pex trace_model
  #      --model-id=$MODEL_ID
  #      --device=cpu
volumes:
  triton_models: